bases:
- ../../base

# set namespace and name prefix
namespace: galaxy-mining
namePrefix: edge-site-a-

# generate secret for BMC access
generatorOptions:
  disableNameSuffixHash: true
  #  annotations:
  #  argocd.argoproj.io/sync-wave: "5"
secretGenerator:
- name: bmc-secret1
  literals:
  - username=admin
  - password=YW1vcmdhbnQK

# replace variables in config files
patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: assisted-deployment-pull-secret
  path: 00-pullsecret.yaml
- target:
    group: extensions.hive.openshift.io
    version: v1beta1
    kind: AgentClusterInstall
    name: edge-site-a-ocpsnospoke-aci
  path: 01-agentclusterinstall.yaml
- target:
    group: hive.openshift.io
    version: v1
    kind: ClusterDeployment
    name: edge-site-a-ocpsnospoke
  path: 02-clusterdeployment.yaml
- target:
    group: agent-install.openshift.io
    version: v1beta1
    kind: NMStateConfig
    name: edge-site-a-assisted-deployment-nmstate-ocpsnospoke
  path: 03-nmstateconfig.yaml
- target:
    group: agent-install.openshift.io
    version: v1beta1
    kind: InfraEnv
    name: edge-site-a-ocpsnospoke-env
  path: 04-infraenv.yaml
- target:
    group: metal3.io
    version: v1alpha1
    kind: BareMetalHost
    name: edge-site-a-edgesno001
  path: 05-bmc.yaml
