apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
 .dockerconfigjson: ""
