apiVersion: batch/v1
kind: Job
metadata:
  name: job-infraenv-image-status-readiness
  namespace: galaxy-mining
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      containers:
      - command:
          - /bin/bash
          - "-c"
          - |
            /bin/bash <<'EOF'
            # Check ISO image creation status
            # Author: Federico 'tele' Rossi <ferossi@redhat.com>
            function logc() {
                txt=$1
                echo -e "[`date '+%m-%-d-%Y %H:%M:%S'`] $txt"
            } 

            ct=0
            INFRAENV_NAME=`oc get infraenv -o template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'`
 
            while [[ $ct -le 30 ]]; do
              IMAGE_STATUS=`oc get infraenv $INFRAENV_NAME -o=jsonpath='{.status.conditions[0].type}'`
              logc "Check ISO image creation status..."
              logc "Output: $IMAGE_STATUS" 
              
              if [[ "$IMAGE_STATUS" == "ImageCreated" ]]; then
                logc "ISO Image successfully created"
                status=1;
                break;
              else
                logc "Image not ready yet.."
                status=0;
              fi
              sleep 10
              ct=$(($ct+1))
            done
            
            if [[ ${status} -eq 1 ]]; then
              logc "ISO Download URL: "
              oc get infraenv $INFRAENV_NAME -o=jsonpath='{.status.isoDownloadURL}' 
              exit 0
            else
              logc "ISO Image creation failed, send notification.."
              # slack, email etc.. notifications
              exit 1
            fi

            EOF
        name: infraenv-image-status-readiness
        image: registry.redhat.io/openshift4/ose-cli
      restartPolicy: Never

