apiVersion: batch/v1
kind: Job
metadata:
  name: infraenv-status-image-readiness
  namespace: galaxy-mining
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "6"
spec:
 template:
   spec:
    containers:
      - name: infraenv-status-image-readiness
        image: registry.redhat.io/openshift4/ose-cli
        command:
          - /bin/bash
          - "-c"
          - |
            /bin/bash -x <<'EOF'
            ct=0
            while [[ $ct -le 30 ]]; do
              if [[ `oc get infraenv edge-site-a-ocpsnospoke-env -n galaxy-mining -o=jsonpath='{.status.conditions[0].type}'` == "ImageCreated" ]]; then
                echo 'matched'
                status=0;
                break;
              else
                echo 'not matched'
                status=1;
              fi
              sleep 10
              ct=$(($ct+1))
            done
            if [[ ${status} -eq 0 ]]; then
              echo 'Success'
              exit 0
            else
              echo 'Send notification imageCreationFailed'
              exit 1
            fi

            EOF
